def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    environment {
        registryCredential = 'ecr:us-east-1:awscred'
        imageName = "637423514026.dkr.ecr.us-east-1.amazonaws.com/vprofileproject"
        vprofileRegistry = "http://637423514026.dkr.ecr.us-east-1.amazonaws.com"
        cluster = "vprofile"
        service = "vprofilesvc"
    }
    stages {
        stage('Fetch Code') {
            steps {
                git branch: 'docker', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }
        }
        stage('BUILD') {
            steps {
                sh 'mvn clean install -Dskip'
            }
            post {
                success {
                    echo 'Now Archiving'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('UNIT TEST') {
            steps {
                sh 'mvn test'
            }
        }
        stage('CHECKSTYLE ANALYSIS') {
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
        }
        stage('Sonarqube Analysis') {
            environment {
                scannerHome = tool 'Sonar6.2'
            }
            steps {
                withSonarQubeEnv('sonarserver') {
                    sh '''${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=vprofile \
                   -Dsonar.projectName=vprofile-repo \
                   -Dsonar.projectVersion=1.0 \
                   -Dsonar.sources=src/ \
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
                   -Dsonar.junit.reportsPath=target/surefire-reports/ \
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }
        stage("Quality Gate") {
            steps {
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
        }
        // stage('Upload Artifact') {
        //     steps {
        //         nexusArtifactUploader(
        //                     nexusVersion: 'nexus3',
        //                     protocol: 'http',
        //                     nexusUrl: '192.168.140.167:8081',
        //                     groupId: 'nexus',
        //                     version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
        //                     repository: 'vprofile-repo',
        //                     credentialsId: 'nexuslogin',
        //                     artifacts: [
        //                         [artifactId: 'vproapp',
        //                         classifier: '',
        //                         file: 'target/vprofile-v2.war',
        //                         type: 'war']
        //                     ]
        //         )
        //     }
        // }
        stage('Build Image') {
            steps {
                script {
                    dockerImage = docker.build( imageName + ":$BUILD_NUMBER", "./Docker-files/app/multistage/")
                }
            }
        }
        stage('Upload App Image') {
            steps {
                script {
                    docker.withRegistry(vprofileRegistry, registryCredential) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Cleanup') {
            steps {
                sh 'docker rmi -f $(docker ps -aq)'
            }
        }
        stage('Container Deployment') {
            steps {
                withAWS(credentails: 'awscred', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }

    }
    post{
        always{
            echo "Slack Notification"
            slackSend channel: '#devops',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}"
        }
    }
}
